name: API Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: 11
      - name: Run API Tests
        run: mvn clean test -Dsuite=api

