name: API Tests

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'synchronize'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run API Tests
        run: mvn clean test -Dsuite=api-testing

